# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_native'),
    ]

    operations = [
        migrations.AddField(
            model_name='native',
            name='session_expired',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='native',
            name='session_id',
            field=models.CharField(default='0', max_length=80),
        ),
    ]
