# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_auto_20160421_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='native',
            name='session_expired',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
