# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_auto_20160421_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='native',
            name='session_expired',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
