# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_auto_20160421_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessionlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=80)),
                ('session_expired', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
