# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssuser',
            name='ssusr_bu',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
