from django.db import models

# Create your models here.


class ctloc(models.Model):
	ctloc_rowid = models.IntegerField(primary_key=True)
	ctloc_code = models.CharField(max_length=220)
	ctloc_desc = models.CharField(max_length=220, blank=True, null=True)
	ctloc_glccc_dr = models.IntegerField(blank=True, null=True)
	ctloc_password = models.CharField(max_length=220, blank=True, null=True)
	ctloc_wardflag = models.CharField(max_length=220, blank=True, null=True)
	ctloc_address = models.CharField(max_length=4096, blank=True, null=True)
	ctloc_activeflag = models.CharField(max_length=220, blank=True, null=True)
	ctloc_cashier_dr = models.IntegerField(blank=True, null=True)
	ctloc_otc_dr = models.IntegerField(blank=True, null=True)
	ctloc_starttime = models.TimeField(blank=True, null=True)
	ctloc_endtime = models.TimeField(blank=True, null=True)
	ctloc_ownqueflag = models.CharField(max_length=220, blank=True, null=True)
	ctloc_recqueflag = models.CharField(max_length=220, blank=True, null=True)
	ctloc_type = models.CharField(max_length=220, blank=True, null=True)
	ctloc_disploc_dr = models.IntegerField(blank=True, null=True)
	ctloc_floor = models.CharField(max_length=220, blank=True, null=True)
	ctloc_nfmi_dr = models.CharField(max_length=254, blank=True, null=True)
	ctloc_laundry = models.CharField(max_length=220, blank=True, null=True)
	ctloc_dep_dr = models.IntegerField(blank=True, null=True)
	ctloc_differentsexpatients = models.CharField(max_length=220, blank=True, null=True)
	ctloc_index = models.CharField(max_length=220, blank=True, null=True)
	ctloc_hospital_dr = models.IntegerField(blank=True, null=True)
	ctloc_executeconfirmation = models.CharField(max_length=220, blank=True, null=True)
	ctloc_dateactivefrom = models.DateField()
	ctloc_dateactiveto = models.DateField(blank=True, null=True)
	ctloc_rehabilitativeflag = models.CharField(max_length=220, blank=True, null=True)
	ctloc_medicalrecordactive = models.CharField(max_length=220, blank=True, null=True)
	ctloc_defaultmrtype_dr = models.IntegerField(blank=True, null=True)
	ctloc_resultdelivery = models.CharField(max_length=220, blank=True, null=True)
	ctloc_respunit_dr = models.IntegerField(blank=True, null=True)
	ctloc_patientagesexmix_dr = models.IntegerField(blank=True, null=True)
	ctloc_intendclincareintensity_dr = models.IntegerField(blank=True, null=True)
	ctloc_broadpatientgroup_dr = models.IntegerField(blank=True, null=True)
	ctloc_weeklyavailindicator = models.CharField(max_length=220, blank=True, null=True)
	ctloc_openovernightindicator = models.CharField(max_length=220, blank=True, null=True)
	ctloc_signiffacility_dr = models.IntegerField(blank=True, null=True)
	ctloc_notused = models.CharField(max_length=220, blank=True, null=True)
	ctloc_extgroup_dr = models.IntegerField(blank=True, null=True)
	ctloc_externalinfosystem = models.CharField(max_length=220, blank=True, null=True)
	ctloc_telephone = models.CharField(max_length=220, blank=True, null=True)
	ctloc_telephoneext = models.CharField(max_length=220, blank=True, null=True)
	ctloc_hl7orderslink = models.CharField(max_length=220, blank=True, null=True)
	ctloc_contactname = models.CharField(max_length=220, blank=True, null=True)
	ctloc_floorplanquery = models.CharField(max_length=220, blank=True, null=True)
	ctloc_visithrfrom = models.TimeField(blank=True, null=True)
	ctloc_visithrto = models.TimeField(blank=True, null=True)
	ctloc_restperiodfrom = models.TimeField(blank=True, null=True)
	ctloc_restperiodto = models.TimeField(blank=True, null=True)
	ctloc_agefrom = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
	ctloc_ageto = models.DecimalField(max_digits=3, decimal_places=0, blank=True, null=True)
	ctloc_nationcode = models.CharField(max_length=220, blank=True, null=True)
	ctloc_orderstorecloc = models.CharField(max_length=220, blank=True, null=True)
	ctloc_sendhl7messageon = models.CharField(max_length=220, blank=True, null=True)
	ctloc_departmentheaduserdr = models.IntegerField(blank=True, null=True)
	ctloc_pagerno = models.CharField(max_length=220, blank=True, null=True)
	ctloc_email = models.CharField(max_length=220, blank=True, null=True)
	ctloc_fax = models.CharField(max_length=220, blank=True, null=True)
	ctloc_daysautogenerate = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_mrrequestmovevalid = models.CharField(max_length=220, blank=True, null=True)
	ctloc_snapflag = models.CharField(max_length=220, blank=True, null=True)
	ctloc_multdaterangesvisithrs = models.CharField(max_length=230, blank=True, null=True)
	ctloc_mentalhealthunit = models.CharField(max_length=220, blank=True, null=True)
	ctloc_preferedoutlierward = models.IntegerField(blank=True, null=True)
	ctloc_wardsinglesex = models.IntegerField(blank=True, null=True)
	ctloc_printlabelsurgmrrequest = models.CharField(max_length=220, blank=True, null=True)
	ctloc_enabledischargeallhyperlink = models.CharField(max_length=220, blank=True, null=True)
	ctloc_inpatientunit = models.CharField(max_length=220, blank=True, null=True)
	ctloc_outpatientunit = models.CharField(max_length=220, blank=True, null=True)
	ctloc_timesincelastappt = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_period = models.CharField(max_length=220, blank=True, null=True)
	ctloc_dischsumnotrequired = models.CharField(max_length=220, blank=True, null=True)
	ctloc_natcodedatefrom = models.DateField(blank=True, null=True)
	ctloc_natcodedateto = models.DateField(blank=True, null=True)
	ctloc_signfacildatefrom = models.DateField(blank=True, null=True)
	ctloc_signiffacildateto = models.DateField(blank=True, null=True)
	ctloc_dischargelounge = models.CharField(max_length=220, blank=True, null=True)
	ctloc_externalviewerlink = models.CharField(max_length=220, blank=True, null=True)
	ctloc_daystokeeprecord = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_nataheadings = models.CharField(max_length=4096, blank=True, null=True)
	ctloc_weekssuspensionreview = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_daysforopdoffer = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_daysforopletterresponse = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_offersbeforeip_opwaitreset = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_daysofferoutcomechange = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ctloc_radordaccessnoprefix = models.CharField(max_length=220, blank=True, null=True)
	ctloc_donotdisplayroomdescforbed = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ebookerid = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ebookingid = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ebookerenabled = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ebookingenabled = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ebookeriurpenabled = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ebookersuspdate = models.DateField(blank=True, null=True)
	ctloc_ebookersuspreas = models.CharField(max_length=4096, blank=True, null=True)
	ctloc_dischsumoprequired = models.CharField(max_length=220, blank=True, null=True)
	ctloc_dischsumiprequired = models.CharField(max_length=220, blank=True, null=True)
	ctloc_dischsumedrequired = models.CharField(max_length=220, blank=True, null=True)
	ctloc_ipdischsummarytype = models.CharField(max_length=220, blank=True, null=True)
	ctloc_opdischsummarytype = models.CharField(max_length=220, blank=True, null=True)
	ctloc_eddischsummarytype = models.CharField(max_length=220, blank=True, null=True)
	ctloc_chargeaccompatientonleave = models.CharField(max_length=220, blank=True, null=True)
	ctloc_communityunit = models.CharField(max_length=220, blank=True, null=True)
	
class ssuser(models.Model):
	ssusr_rowid = models.IntegerField(primary_key=True)
	ssusr_initials = models.CharField(max_length=220)
	ssusr_name = models.CharField(max_length=220)
	ssusr_password = models.CharField(max_length=220)
	ssusr_defaultdept_dr = models.ForeignKey(ctloc, blank=True, null=True,related_name='deptdata',db_column = "ssusr_defaultdept_dr")
	ssusr_isthisdoctor = models.CharField(max_length=220, blank=True, null=True)
	ssusr_usedeptasdefault = models.CharField(max_length=220, blank=True, null=True)
	ssusr_ctpcp_dr = models.CharField(max_length=220, blank=True, null=True)
	ssusr_group = models.IntegerField()
	ssusr_changelocation = models.CharField(max_length=220, blank=True, null=True)
	ssusr_emailname = models.CharField(max_length=220, blank=True, null=True)
	ssusr_deptforemrlists = models.IntegerField(blank=True, null=True)
	ssusr_ctlan_dr = models.IntegerField(blank=True, null=True)
	ssusr_careprov_dr = models.CharField(max_length=220, blank=True, null=True)
	ssusr_pin = models.CharField(max_length=220, blank=True, null=True)
	ssusr_privilegestock = models.CharField(max_length=220, blank=True, null=True)
	ssusr_retainordercategory = models.CharField(max_length=220, blank=True, null=True)
	ssusr_lastpaadm_dr = models.IntegerField(blank=True, null=True)
	ssusr_active = models.CharField(max_length=220, blank=True, null=True)
	ssusr_drgtariffvisible = models.CharField(max_length=220, blank=True, null=True)
	ssusr_billsequence_dr = models.IntegerField(blank=True, null=True)
	ssusr_searchalladm = models.CharField(max_length=220, blank=True, null=True)
	ssusr_inpatient = models.CharField(max_length=220, blank=True, null=True)
	ssusr_outpatient = models.CharField(max_length=220, blank=True, null=True)
	ssusr_emergency = models.CharField(max_length=220, blank=True, null=True)
	ssusr_ownpatientsonly = models.CharField(max_length=220, blank=True, null=True)
	ssusr_loclist_dr = models.IntegerField(blank=True, null=True)
	ssusr_autoauthorise = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defaultarcim_dr = models.CharField(max_length=254, blank=True, null=True)
	ssusr_defrbdepartment_dr = models.IntegerField(blank=True, null=True)
	ssusr_defrbresource_dr = models.IntegerField(blank=True, null=True)
	ssusr_defrbservice_dr = models.IntegerField(blank=True, null=True)
	ssusr_defepisode = models.CharField(max_length=220, blank=True, null=True)
	ssusr_linktobedmanagement = models.CharField(max_length=220, blank=True, null=True)
	ssusr_usedefaultepisdep = models.CharField(max_length=220, blank=True, null=True)
	ssusr_warnorbookingmoveres = models.CharField(max_length=220, blank=True, null=True)
	ssusr_nallorbookpast = models.CharField(max_length=220, blank=True, null=True)
	ssusr_nallorbooknosess = models.CharField(max_length=220, blank=True, null=True)
	ssusr_nallorbookna = models.CharField(max_length=220, blank=True, null=True)
	ssusr_alwaysusesoundex = models.CharField(max_length=220, blank=True, null=True)
	ssusr_rbnumberofrows = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ssusr_multiselectrows = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ssusr_passworddate = models.DateField(blank=True, null=True)
	ssusr_datelastlogin = models.DateField(blank=True, null=True)
	ssusr_timelastlogin = models.TimeField(blank=True, null=True)
	ssusr_datefromtoday = models.CharField(max_length=220, blank=True, null=True)
	ssusr_datetotoday = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defrefhosp_dr = models.IntegerField(blank=True, null=True)
	ssusr_resentrybuttons = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defaultresentrybuttons = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defdateinoe = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defdateindisch = models.CharField(max_length=220, blank=True, null=True)
	ssusr_disableemrpreadm = models.CharField(max_length=220, blank=True, null=True)
	ssusr_searchprevadm = models.CharField(max_length=220, blank=True, null=True)
	ssusr_noorders = models.CharField(max_length=220, blank=True, null=True)
	ssusr_noemr = models.CharField(max_length=220, blank=True, null=True)
	ssusr_nodiagnosis = models.CharField(max_length=220, blank=True, null=True)
	ssusr_websecurityaccess = models.CharField(max_length=220, blank=True, null=True)
	ssusr_epissubtype_dr = models.IntegerField(blank=True, null=True)
	ssusr_notreadresults = models.CharField(max_length=220, blank=True, null=True)
	ssusr_restrictmodifdischarge = models.CharField(max_length=220, blank=True, null=True)
	ssusr_booked = models.CharField(max_length=220, blank=True, null=True)
	ssusr_admitted = models.CharField(max_length=220, blank=True, null=True)
	ssusr_discharged = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defaultcareprov = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defaultlocation = models.CharField(max_length=220, blank=True, null=True)
	ssusr_passwordchanged = models.CharField(max_length=220, blank=True, null=True)
	ssusr_title = models.CharField(max_length=220, blank=True, null=True)
	ssusr_surname = models.CharField(max_length=220, blank=True, null=True)
	ssusr_givenname = models.CharField(max_length=220, blank=True, null=True)
	ssusr_othername = models.CharField(max_length=220, blank=True, null=True)
	ssusr_departmenthead = models.CharField(max_length=220, blank=True, null=True)
	ssusr_payrollnumber = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ssusr_stafftype_dr = models.IntegerField(blank=True, null=True)
	ssusr_comments = models.CharField(max_length=4096, blank=True, null=True)
	ssusr_lastupdateuser_dr = models.IntegerField(blank=True, null=True)
	ssusr_lastupdatedate = models.DateField(blank=True, null=True)
	ssusr_lastupdatetime = models.TimeField(blank=True, null=True)
	ssusr_doctorflag = models.CharField(max_length=220, blank=True, null=True)
	ssusr_nurseflag = models.CharField(max_length=220, blank=True, null=True)
	ssusr_securitymsgread = models.CharField(max_length=220, blank=True, null=True)
	ssusr_securitymessage = models.CharField(max_length=4096, blank=True, null=True)
	ssusr_loginid = models.CharField(max_length=220, blank=True, null=True)
	ssusr_loginround = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defallresources = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defapptslots = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defusestarttimeeachday = models.CharField(max_length=220, blank=True, null=True)
	ssusr_defappointmeth_dr = models.IntegerField(blank=True, null=True)
	ssusr_title_dr = models.IntegerField(blank=True, null=True)
	ssusr_registrationnumber = models.CharField(max_length=220, blank=True, null=True)
	ssusr_printsecuritylevel = models.CharField(max_length=220, blank=True, null=True)
	ssusr_lastupdateuserhosp_dr = models.IntegerField(blank=True, null=True)
	ssusr_changelocwithinloghosp = models.CharField(max_length=220, blank=True, null=True)
	ssusr_notallowtooverbook = models.CharField(max_length=220, blank=True, null=True)
	ssusr_markinactivedate = models.DateField(blank=True, null=True)
	ssusr_markinactivetime = models.TimeField(blank=True, null=True)
	ssusr_markinactiveuser_dr = models.IntegerField(blank=True, null=True)
	ssusr_datefrom = models.DateField(blank=True, null=True)
	ssusr_dateto = models.DateField(blank=True, null=True)
	ssusr_hospital_dr = models.IntegerField(blank=True, null=True)
	ssusr_mobile = models.CharField(max_length=220, blank=True, null=True)
	ssusr_pager = models.CharField(max_length=220, blank=True, null=True)
	ssusr_email = models.CharField(max_length=220, blank=True, null=True)
	ssusr_locationnotmandatoryonresentry = models.CharField(max_length=220, blank=True, null=True)
	ssusr_timesincelastappt = models.DecimalField(max_digits=15, decimal_places=0, blank=True, null=True)
	ssusr_timesinceperiod = models.CharField(max_length=220, blank=True, null=True)
	ssusr_name1 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_name2 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_name3 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_iepath = models.CharField(max_length=220, blank=True, null=True)
	ssusr_externaluseridentifier = models.CharField(max_length=220, blank=True, null=True)
	ssusr_cashiershift = models.CharField(max_length=220, blank=True, null=True)
	ssusr_biokey = models.CharField(max_length=220, blank=True, null=True)
	ssusr_biomode = models.CharField(max_length=220, blank=True, null=True)
	ssusr_disclaimersigned = models.DateField(blank=True, null=True)
	ssusr_createdby_dr = models.IntegerField(blank=True, null=True)
	ssusr_createddate = models.DateField(blank=True, null=True)
	ssusr_createdtime = models.TimeField(blank=True, null=True)
	ssusr_yesno1 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_yesno2 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_yesno3 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_yesno4 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_yesno5 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_freetext1 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_freetext2 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_freetext3 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_allowweblayoutmanager = models.CharField(max_length=220, blank=True, null=True)
	ssusr_allowwebcolumnmanager = models.CharField(max_length=220, blank=True, null=True)
	ssusr_externalid2 = models.CharField(max_length=220, blank=True, null=True)
	ssusr_treatmentpathwayowner = models.CharField(max_length=220, blank=True, null=True)
	ssusr_treatmentstageowner = models.CharField(max_length=220, blank=True, null=True)

	#def __str__(self):
	#	return self.ssusr_initials
		